# Generated by Django 3.0.5 on 2020-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredsensors",
            name="display_name",
            field=models.TextField(default="not_set", max_length=255),
        ),
        migrations.AlterField(
            model_name="registeredsensors",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
