# Generated by Django 3.0.5 on 2020-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loggeddata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeddata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
