# Generated by Django 3.0.6 on 2020-05-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200508_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeddata',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loggeddata',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
